<a href="https://colab.research.google.com/github/srikrishna-stack/python-problem-solving/blob/main/hackerrankproblems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#factorial of a number
def factorial (n):
  if (n==0 or n==1):
    return 1
  else:
    return n*foactorial (n-1)
print(factorial (5))




120


In [ ]:
def compound_intrest(principle,rate,time):
  amount=principle*(pow((1 + rate / 100), time))
  ci=amount-time
  print("compound intrest is",ci)
compound_intrest(10000,10.25,5)




compound intrest is 16283.946267774416


In [ ]:
#to calculate the amstrong number or not
num=int(input("enter the value"))
temp=num
sum=0
while (temp>0):
  digit=temp % 10
  sum+=digit**3
  temp//=10
if num==sum:
  print("it is a amstrong number")
else :
  print("it is not a amstrong number")
#amstrong of n digits



enter the value123
it is not a amstrong number
this is not the amsdtong number


In [ ]:
num1=int(input("enter the value"))
order=len(str(num1))
sum=0
temp=num1
while (temp>0):
  digit=temp%10
  sum+=digit** order
  temp//=10
if(num1==sum):
  print("amstrong number")
else:
  print("this is not the amsdtong number")


enter the value1634
amstrong number


In [ ]:
#python program to print prime number
start=11
end=25
for i in range(start,end+1):
  for j in range(2,i):
    if i%j==0:
      break
  else:
    print(i)


11
13
17
19
23


In [ ]:
p1=int(input("enter the number"))
if p1 >1:
  for i in range(2,int(p1/2)+1):
    if p1%i==0:
      print("p1 is not a prime number")
      break
  else:
    print(p1,"it is a prime number")
else:
  print("it is not a prime number")


enter the number3
3 it is a prime number


In [ ]:
#fibonacci serires
def fibonaci(n):
  a=0
  b=1
  if (n<0):
    print("incorrect input")
  elif n==0:
    return a
  elif n==1:
    return b
  else:
    for i in range(2,n):
      i=a+b
      a=b
      b=i
    return b

print (fibonaci(9))

21


In [ ]:
c='g'
print("the ASCII value of  c is ",c,ord(c))

the ASCII value of  c is  g 103


In [ ]:
#sum of first natural numbers
def squaresum(n):
  sum=0
  for i in range(1,n+1):
    sum+=i*i
  return sum
print(squaresum(5))

55


In [ ]:
#program to find the sum of array
import array as arr
arr=arr.array('i',[1,2,3,4])
sum=0
for i in arr:
  sum=sum+i
print(sum)
max=arr[0]
for i in range(len(arr)):
  arr[i]>max
  max=arr[i]
print(max)
  

  


10
4


In [ ]:
def rotation_array(arr,n,d):
  temp=[]
  i=0
  while(i<d):
    temp.append(arr[i])
    i=i+1
  i=0
  while(d<n):
    arr[i]=arr[d]
    i=i+1
    d=d+1
  arr[:]=arr[:i]+temp
  return arr
arr=[1,2,3,4,5,6,7]
print('this is the original array',arr)
print('array after left rotation')
print(rotation_array(arr,len(arr),2))

this is the original array [1, 2, 3, 4, 5, 6, 7]
array after left rotation
[3, 4, 5, 6, 7, 1, 2]


In [ ]:
def findremainder(arr, lens, n):
    mul = 1
 
    # find the individual
    # remainder and
    # multiple with mul.
    for i in arr:
        mul = mul *i
 
    return mul % n
 
 
# Driven code
arr = [100, 10, 5, 25, 35, 14]
lens = len(arr)
n = 11
print(findremainder(arr, lens, n))

9


In [ ]:
def isMonotonic(A):
  
    return (all(A[i] <= A[i + 1] for i in range(len(A) - 1)) or
            all(A[i] >= A[i + 1] for i in range(len(A) - 1)))
A = [6, 5, 4, 4]
print(isMonotonic(A))

True


In [ ]:
#swaping the elements in the list
def swap_element(list1):
  n= len(list1)
  temp=list1[0]
  list1[0]=list1[n-1]
  list1[n-1]=temp
  return list1
  
list1=[1,2,3,4,5,6]
print("list before swapping",list1)
print(swap_element(list1))

list before swapping [1, 2, 3, 4, 5, 6]
[6, 2, 3, 4, 5, 1]


In [ ]:
list1=[2,3,1,4,5,6]
list1.sort()
print(list1[:1])

[1]


In [ ]:
import sys
a=int(input())
b=int(input())
print(a//b)
print(a/b)




4
3
1
1.3333333333333333


In [ ]:
#TO print leap year
def is_leap(year):
    leap = False
    if (year==2100):
      return leap
    if (year%4==0):
        return True
    if (year%400==0):
        return True
    
    else:
        return leap
year = int(input())
print(is_leap(year))

2100
False


In [ ]:
n=int(input())
for i in range(n):
  print(i+1,end="")

3
123

In [ ]:
    class EvenStream(object):
        def __init__(self):
            self.current = 0

        def get_next(self):
            to_return = self.current
            self.current += 2
            return to_return

    class OddStream(object):
        def __init__(self):
            self.current = 1

        def get_next(self):
            to_return = self.current
            self.current += 2
            return to_return

    def print_from_stream(n, stream=None):
        stream = OddStream() if stream else EvenStream()
        for _ in range(n):
            print(stream.get_next())


    queries = int(input())
    for _ in range(queries):
        stream_name, n = input().split()
        n = int(n)
        if stream_name == "even":
            print_from_stream(n)
        else:
            print_from_stream(n, OddStream())


3
even 3
0
2
4
odd 2
1
3
odd 5
1
3
5
7
9


In [ ]:
def lexnumbers(n):
  s=[]
  for i in range(1,n+1):
    s.append(str(i))
  s.sort()
  ans=[]
  for i in range(n):
    ans.append(int(s[i]))
  for i in range(n):
    print(ans[i],end=" ")
  
if __name__=="__main__":
  n=15
  lexnumbers(n)

1 10 11 12 13 14 15 2 3 4 5 6 7 8 9 

In [ ]:
if __name__=="__main__":
  x=int(input())
  y=int(input())
  z=int(input())
  n=int(input())
  output=[]
  abc=[]
  for x in range(x+1):
    for y in range(y+1):
      for z in range(z+1):
        if x+y+z!=n:
          abc=[x,y,z]
          output.append(abc)
print(output)

1
1
1
2
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]


In [ ]:
input_string=(input())
print('Hello, World')
print(input_string)

Welcome to 30 Days of Code!
Hello, World
Welcome to 30 Days of Code!


In [ ]:
n=int(input())
ans=map(int,input().split())
print (sorted(list(set(ans)))[-2])

5
2 3 6 6 5
5


In [ ]:
score_list=[]
for _ in range(int(input())):
  name=input()
  score=float(input())
  score_list.append([name,score])
second_highest=sorted(set[score for name,score in score_list]))[1]
print('\n'.join(sorted([name for name,score in score_list if score==second_highest])))


SyntaxError: ignored

In [ ]:
harry bina teena ankit harsh
37.2137.2137.24139

SyntaxError: ignored

In [ ]:
score_list = []
for _ in range(int(input())):
    name = input()
    score = float(input())
    score_list.append([name, score])
second_highest = sorted(set([score for name, score in score_list]))[1]
print('\n'.join(sorted([name for name, score in score_list if score == second_highest])))


3]]3[


ValueError: ignored

In [ ]:
#list problem
T = int(input().strip())

L = []
for t in range(T):
    args = input().strip().split(" ")
    if args[0] == "append":
        L.append(int(args[1]))
    elif args[0] == "insert":
        L.insert(int(args[1]), int(args[2]))
    elif args[0] == "remove":
        L.remove(int(args[1]))
    elif args[0] == "pop":
        L.pop()
    elif args[0] == "sort":
        L.sort()
    elif args[0] == "reverse":
        L.reverse()
    elif args[0] == "print":
        print(L)


12
append


IndexError: ignored

In [ ]:
#hash functon in tuple
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    tuple_list=tuple(integer_list)
    print(hash(tuple_list))

2
12
3430014387543


In [ ]:
#textwrap function
import textwrap
def text_wrap(string,max_width):
  return textwrap.fill(string,max_width)
if __name__=="__main__":
  string=input()
  max_width=int(input())
  result=text_wrap(string,max_width)
  print(result)


abcdefghijklmnopqrstuvwxyz
4
abcd
efgh
ijkl
mnop
qrst
uvwx
yz


In [ ]:
import textwrap
def text_wrap(string,max_width):
  return textwrap.fill(string,max_width)
if __name__=="__main__":
  string,max_width=input(),int(input())
  result=text_wrap(string,max_width)
  print(result)


abcdefghjklmnopqrstuvwxyz 4



ValueError: ignored

In [ ]:
N=int(input())
M=int(input())
for i in range(1,N,2):
  print('*'*i).center(M,'-')
print('welcome').center(M,'-')
for i in range(N-2,-1,-2):
  print('*'*i).center(M,'-')


9
34
*


AttributeError: ignored

In [ ]:
'''Mr. Vincent works in a door mat manufacturing company. One day, he designed a new door mat with the following specifications:

   # Mat size must be 

X. ( is an odd natural number, and is times
.)
The design should have 'WELCOME' written in the center.
The design pattern should only use |, . and - characters.'''
N,M=map(int,input())
for i in range(1,N,2):
  print('.|.'*i).center(M,'-')
print('welcome').center(M,'-')
for i in range(N-1,-1,-2):
  


In [ ]:
#swap case
def swap_case(s):
  return s.swapcase()
 ''' output=''
  for char in s:
    if (char.isupper==True):
      output+=(char.lower())
    elif (char.islower==True):
      output+=(char.upper())
    else:
      output+=char
  return output'''
  
if __name__=="__main__":
  s=input()
  result=swap_case(s)
  print(result)


IndentationError: ignored

In [ ]:
def split_and_join(line):
    line=line.split()
    return "-".join(line)
    
if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print (result)


this is a string
this-is-a-string


In [ ]:
def print_full_name(first, last):
    # Write your code here
    print('Hello'+' '+first_name+last_name+ ' '+'!' +'You just delved into python',end="")

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

Ross
Taylor'
Hello RossTaylor' !You just delved into python

In [ ]:
#mutation
def mutate_string(string, position, character):
    l=list(string)
    l[position]=character
    string=''.join(l)
    return string
   

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

SyntaxError: ignored

In [ ]:
def func1(s):
  for i in range(len(s)):
    if (s[i].isalnum()):
      return True
      break
  return False
def func2(s):
  for i in range(len(s)):
    if (s[i].isalpha()):
      return True
      break
  return False
def fun3(s):
  for i in range(len(s)):
    if s[i].isdigit():
      return True
      break
  return False
def fun4(s):
  for i in range(len(s)):
    if s[i].islower():
      return True
      break
  return False
def fun5(s):
  for i in range(len(s)):
    if s[i].isupper():
      return True
      break
  return False
    

if __name__=="__main__":
  s=input()
  isalnumeric=func1(s)
  isalphabetical=func2(s)
  isdigits=fun3(s)
  islower=fun4(s)
  isupper=fun5(s)
  print(isalnumeric)
  print(isalphabetical)
  print(isdigits)
  print(islower)
  print(isupper)

123


NameError: ignored

In [ ]:
def count_substring(string, sub_string):
    count=0
    for i in range((len(string)-len(sub_string))+1):
        if(string[i:i+len(sub_string)]==sub_string):
            count=count+1
    return count
 
def countTotalBits(num):
     
     # convert number into it's binary and
     # remove first two characters 0b
if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

abcdd
cd
1


In [ ]:
bi=hex(10)[2:]
print(bi)

a


In [ ]:
l1=(bin(17))[2:]
print(l1)

10001


In [ ]:
txt = "banana"

x = txt.rjust(20)

print(x, "is my favorite fruit.") 

              banana is my favorite fruit.


In [ ]:
n=int(input())
l1 = len(bin(n)[2:])
for i in range(1,n+1):
  print(str(i).rjust(l1,' '),end=" ")

   
   

17
    1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16    17 

In [ ]:
def print_formatted(n):
    l1=len((bin(n))[2:])
    for i in range(1,n+1):
        print(str(i).rjust(l1,' '),end=" ")
        print(((oct(i)[2:]).upper()).rjust(l1,' '),end=" ")
        print ((hex(i)[2:]).rjust(l1,' '),end=" ")
        print ((bin(i)[2:]).rjust(l1,' '),end=" ")
        print(" ")
    

if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

17
    1     1     1     1  
    2     2     2    10  
    3     3     3    11  
    4     4     4   100  
    5     5     5   101  
    6     6     6   110  
    7     7     7   111  
    8    10     8  1000  
    9    11     9  1001  
   10    12     a  1010  
   11    13     b  1011  
   12    14     c  1100  
   13    15     d  1101  
   14    16     e  1110  
   15    17     f  1111  
   16    20    10 10000  
   17    21    11 10001  


In [ ]:
#restuarant problem
def solve(meal_cost, tip_percent, tax_percent):
    tip=(meal_cost/100)*20
    print (tip)
    tax=(tax_percent/100)*meal_cost
    print(tax)
    total_cost=meal_cost+tip+tax
    return round(total_cost)#round function gives the int value
    

if __name__ == '__main__':
    meal_cost = float(input().strip())

    tip_percent = int(input().strip())

    tax_percent = int(input().strip())

    print(solve(meal_cost, tip_percent, tax_percent))
    


12.00
20
8
2.4
0.96
15


In [ ]:
a=(8/100)*20
print(a)

1.6


In [ ]:
#alphabhetic rangoli
'''--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------'''


In [ ]:
for i in range(0,10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(0,0,-1):
  print(i)

In [ ]:
print(chr(97))

a


In [ ]:
def print_rangoli(size):
  width=size*4-3
  string=''
  for i in range(1,n+1):
    for j in range(0,i):
      string+=chr(96+size-j)
      if len(string)<width:
        string+='-'
      print(string.center(width,'-'))
      string=""
  for i in range(size-1,0,-1):
    string = ''
    for j in range(0,i):
      string += chr(96+size-j)
      if len(string) < width :
        string += '-'
      for k in range(i-1,0,-1):
        string += chr(97+size-k)
        if len(string) < width :
          string += '-'
        print(string.center(width,'-'))

  
if __name__ =="__main__":
  n=int(input())
  print_rangoli(n)

3
----c----
----c----
----b----
----c----
----b----
----a----
---c-c---
-c-c-b-c-


In [ ]:
import string
alpha = string.ascii_lowercase
print(alpha)

n = int(input())   
L = []
for i in range(n):
    s = "-".join(alpha[i:n])
    L.append((s[::-1]+s[1:]).center(4*n-3, "-"))
   
print('\n'.join(L[:0:-1]+L))



abcdefghijklmnopqrstuvwxyz
3
----c----
--c-b-c--
c-b-a-b-c
--c-b-c--
----c----


In [ ]:
import string
alpha =string.ascii_lowercase
n=int(input())
L=[]
for i in range(n):
  s='-'.join(alpha[i:n])
  print(s)
  L.append((s[::-1]+s[1:]).center(4*n-3,"-"))
print('\n'.join(L[:0:-1]+L))
  

3
a-b-c
b-c
c
----c----
--c-b-c--
c-b-a-b-c
--c-b-c--
----c----


In [ ]:
b=[1,2,3,4,5]
print(b[1:3])

[2, 3]


In [ ]:
for i in range(3):
  print(i)

0
1
2


In [ ]:
s=input()
print(s.split())

hello world
['hello', 'world']


In [ ]:
import os
import sys
def solve(s):
    for  i in s.split():
        s=s.replace(i,i.capitalize(i))
    return s

    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()

KeyError: ignored

In [ ]:
def minion_game(s):
  vowels = 'AEIOU'

  kevsc = 0
  stusc = 0
  for i in range(len(s)):
    if s[i] in vowels:
      kevsc += (len(s)-i)
      
    else:
        stusc += (len(s)-i)

  if kevsc > stusc:
    print("Kevin", kevsc)
  elif kevsc < stusc:
    print("Stuart", stusc)
  else:
    print("Draw")

if __name__=="__main__":
  s=input()
  minion_game(s)

BANABA
Stuart 12


In [ ]:
num = list(range(10))
previousNum = 0
for i in num:
    sum = previousNum + i
    print('Current Number '+ str(i) + 'Previous Number ' + str(previousNum) + 'is ' + str(sum)) 
    previousNum=i


Current Number 0Previous Number 0is 0
Current Number 1Previous Number 0is 1
Current Number 2Previous Number 1is 3
Current Number 3Previous Number 2is 5
Current Number 4Previous Number 3is 7
Current Number 5Previous Number 4is 9
Current Number 6Previous Number 5is 11
Current Number 7Previous Number 6is 13
Current Number 8Previous Number 7is 15
Current Number 9Previous Number 8is 17


In [ ]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:

def solve(s):
    for  i in s.split():
        s=s.replace(i,i.capitalize())
    return s       
s=input()            
print(solve(s))

pavitha is rich kid
Pavitha Is Rich Kid


In [ ]:
class Person:
    def __init__(self, initialAge):
        if initialAge > 0:
            self.age = initialAge
        else:
            print("Age is not valid, setting age to 0.")
            self.age = 0

    def amIOld(self):
        if self.age < 13:
            print("You are young.")
        elif self.age < 18:
            print("You are a teenager.")
        else:
            print("You are old.")

    def yearPasses(self):
        self.age += 1


t = int(input())
for i in range(0, t):
    age = int(input())
    p = Person(age)
    p.amIOld()
    for j in range(0, 3):
        p.yearPasses()
    p.amIOld()
    print("")

In [ ]:
if __name__ == '__main__':
    n = int(input().strip())
    for i in range(1,11):
        print(n ,"X",i,"=",n*i)


2
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
2 X 10 = 20


In [ ]:
if __name__ == '__main__':
    n = int(input().strip())
    for i in range(1,11):
        print(n,"X",i,"=",n*i)
       

2
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
2 X 10 = 20


In [ ]:
def Merge_the_tools(string,k):
  for i in range(0,len(string),k):
    line=string[i:i+k]
    seen=set()
    for i in line:
      if i not in seen:
        print(i,end="")
        seen.add(i)
    print()
if __name__=="__main__":
  string=input()
  k=int(input())
  Merge_the_tools(string,k)

AABCAAADA
3
AB
CA
AD


In [ ]:
33333

33333

In [ ]:
def fibonacci(n):
    a=0
    b=0
    if (n==0):
       return a
   
    elif (n==1):
       return b
       
    else:
      for i in range(2,n):
         i=a+b
         a=b
         b=i
      return b
       
        
if __name__=="__main__":
  n=int(input())
  print(fibonacci(n))


5
0


In [ ]:
#map and lambda
cube = lambda x: x**3# complete the lambda function 

def fibonacci(n):
    if n<2:
        return range(n)
    init=[0,1]
    for i in range(0,n-2):
        add=init[i+1]+init[i]
        init.append(add)
    return init
        
    
    
    

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

5
[0, 1, 1, 8, 27]


In [ ]:
#colections.counter

import collections

numShoes = int(input())
shoes = collections.Counter(map(int, input().split()))
numCust = int(input())

income = 0

for i in range(numCust):
    size, price = map(int,input().split())
    if shoes[size]: 
        income += price
        shoes[size] -= 1

print(income)


10
2 3 4 5 6 8 7 6 5 18
6
6 55
6 45
6 55
4 40
18 60
10 50
200


In [ ]:
if __name__=="__main__":
  x=int(input())
  y=int(input())
  z=int(input())
  n=int(input())
  output=[]
  abc=[]
  for x in range(x+1):0,1
    for y in range(y+1):0,1
      for z in range(z+1):0,1
        if x+y+z!=n:
          abc=[x,y,z]
          output.append(abc)
print(output)
ctr = 0

  for word in words:
    if len(word) > 1 and word[0] == word[-1]:
      ctr += 1
  return ctr

1
1
1
2
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]


In [ ]:
x=[24,54,64,74]
max=x[0]
for i in x:
  if (i>max):
    max=i  
print(max)

74


In [ ]:
x=["abc","aba","xyx","xyz"] 
count=0 
for i in x:
  if(len(x)>1 and i[0]==i[-1]): 
    count=count+1
print(count)

2


In [ ]:
def average(arr):
  arr=set(arr)
  return sum(arr)/len(arr)

if __name__=="__main__":
  n=int(input())
  arr=list(map(int,input().split()))
  result=average(arr)
  print(result)

10
161 182 161 154 176 170 167 171 170 174 
169.375


In [ ]:
#symmetric difference
a,b=(int(input()),input().split())
c,d=(int(input()),input().split())
x=set(b)
y=set(d)
p=y.difference(b)
q=x.difference(y)
r=p.union(q)
print('\n'.join(sorted(r,key=int)))

In [ ]:
from collections import defaultdict

n,m = list(map(int,input().split()))
d = defaultdict(list)
for i in range(n):
    d[input()].append(i+1)
for i in range(m):
    print(*d[input()] or [-1])

5 2
a
a
b
a
a
a
1 2 4 5
b
3


In [ ]:
from collections import namedtuple
N = int(input())
fields = input().split()

total = 0
for i in range(N):
    students = namedtuple('student',fields)
    field1, field2, field3,field4 = input().split()
    student = students(field1,field2,field3,field4)
    print(student)
    total += int(student.MARKS)
print('{:.2f}'.format(total/N))


5
ID MARKS NAME CLASS
1          97         Raymond    7    
student(ID='1', MARKS='97', NAME='Raymond', CLASS='7')


KeyboardInterrupt: ignored

In [ ]:

n=int(input())
arr=list(map(int,input().rstrip().split()))
print(" ".join(map(str,arr[::-1])))

4
1 2  3 4
4 3 2 1


In [ ]:
n=int(input())
name_numbers=[input().split() for i in range(n)]
phone_book={k:v for k,v in name_numbers}
while True:
  try:
    name=input()
    if name in phone_book:
      print("%s=%s"%(name,phone_book[name]))
    else:
      print('not found')
  except:
    break


3
sam 99912222
tom 11122222
harry 12299933
sam
sam=99912222
edward
not found
harry
harry=12299933


In [ ]:
for i in range(int(input())):
  try:
    a,b=map(int,input().split())
    print(a//b)
  except Exception as e:
    print("Error code",e)



3
1 0
Error code integer division or modulo by zero
2 $
Error code invalid literal for int() with base 10: '$'
3 1
3


In [ ]:
import math
ab=int(input())
bc=int(input())
print (str(int(round(math.degrees(math.atan2(ab,bc)))))+'°')


10
10
45°


In [ ]:
print(round(math.degrees(math.atan2(10,10))))


45


In [ ]:
items=set()
for i in range(int(input())):
  items.add(input())
print(len(items))

7
UK
China
USA
France
New Zealand
UK
France
5


In [ ]:
variable='15'
print("the varible is =%s"%(variable))

print(variable)

the varible is =15
15


In [ ]:
string="pavithra"
print(string)

pavithra


In [ ]:
lis=[2]
print("the list in %r"%(lis))

the list in [2]
[2]


In [ ]:
from string import  Template
t=Template('x is $x')
print(t.substitute({'x':1234}))

x is 1234


In [ ]:
from string import Template
 
template = Template('$name is the $job of $company')
 
string = template.safe_substitute(name='Raju Kumar',
                      job='TCE')
print(string)

Raju Kumar is the TCE of $company


In [ ]:
from collections import  Counter
stri='geeksforgeeks'
print(Counter(stri))


Counter({'e': 4, 'g': 2, 'k': 2, 's': 2, 'f': 1, 'o': 1, 'r': 1})


In [ ]:
s="geeksforgeeks"
print(reversed(s))

In [ ]:
print(len(max(bin(int(input().strip()))[2:].split('0'))))

223
5


In [ ]:
#deque functions

from collections import deque
d=deque()
for _ in range(int(input())):
    inp=input().split()
    getattr(d,inp[0])(*[inp[1]]if len(inp)>1 else [])
print(*[item for item in d])

6
append 1
append 2
append 3
appendleft 4
pop
popleft
1 2


In [ ]:
from collections import deque
def check(d):
  while d:
    big= d.popleft if d[0]>d[1] else d.pop()
    if not d:
      return "yes"
    if d[-1]>(big) or d[0]>(big):
      return "No"
            
for i in range(int(input())):
  int(input())
  d=deque(map(int,input().split()))
  print(check(d))

2
6
4 3 2 1 3 4


TypeError: ignored

In [ ]:
from collections import deque
def check(d):
    while d:
        big = d.popleft() if d[0]>d[-1] else d.pop()
        if not d:
            return "Yes"
        if d[-1]>big or d[0]>big:
            return "No"
    
for i in range(int(input())):
    int(input())
    d = deque(map(int,input().split()))
    print(check(d))

2
6
4 3 2 1 3 4
Yes
3
1 3 2
No


In [ ]:
from collections import Counter,OrderedDict
class OrderedCounter(Counter,OrderedDict):
  pass
[print(*c) for c in OrderedCounter(sorted(input())).most_common(3)]


aabbbccde
b 3
a 2
c 2


[None, None, None]

In [ ]:
n=int(input())
s=set(map(int,input().split()))
for i in range(int(input())):
  eval('s.{0}({1})'.format(*input().split()+['']))
print(sum(s))

9
123456789
10
pop 
remove9


AttributeError: ignored

In [ ]:
#set union

print(len((set(input().split()) if input() != '-1' else '')|(set(input().split()) if input() != '-1' else '')))

9
1 2 3 4 5  6 7 8 9
9
10 1 2 3 11 21 55 6 8
13


In [ ]:
#set intersection operation
print(len((set(input().split()) if input()!= '-1' else " ")&(set(input().split())if input()!= '-1' else  " ")))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


In [ ]:
#set difference
print(len((set(input().split()) if input()!= '-1' else " ")-(set(input().split())if input()!= '-1' else  " ")))

In [ ]:
#symmetric difference
print(len((set(input().split()) if input()!='-1' else " ")^(set(input().split())if input()!='-1' else " ")))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 2 55 6 8
7


In [ ]:
lis=[["orange",'apple'],['strawberry']]
print(lis[0][1])
print(lis[1][0])

apple
strawberry


In [ ]:
odd=[i**2 for i in range(1,11) if i%2==1]
print(odd)

[1, 9, 25, 49, 81]


In [ ]:
for i in range(1,11):
  if i%2==1:
    print(i**2,end=" ")
   

1 9 25 49 81 

In [ ]:
#set mutation
a = int(input())
A = set(map(int, input().split(' ')))
for i in range(int(input())):
    s, b = input().split(' ')
    if s == 'intersection_update':
        A &= set(map(int, input().split(' ')))
    elif s == 'update':
        A |= set(map(int, input().split(' ')))
    elif s == 'symmetric_difference_update':
        A ^= set(map(int, input().split(' ')))
    else:
        A -= set(map(int, input().split(' ')))
print(sum(A))

In [ ]:
_= int(input())
s1 = set(map(int, input().split()))
N = int(input()) 
for _ in range(N):
    cmd, _ = input().split()
    s2 = set(map(int, input().split()))
    if(cmd == "intersection_update"):
        s1.intersection_update(s2)
    elif(cmd == "update"):
        s1.update(s2)
    elif(cmd == "symmetric_difference_update"):
        s1.symmetric_difference_update(s2)
    elif(cmd == "difference_update"):
        s1.difference_update(s2)
print(s1)

print(sum(s1))


KeyboardInterrupt: ignored

In [ ]:
#cpatain room

k,arr = int(input()),list(map(int, input().split()))

myset = set(arr)


print(((sum(myset)*k)-(sum(arr)))//(k-1))

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
{1, 2, 3, 4, 5, 6, 8}
8


In [ ]:
from collections import Counter
k=int(input())
arr = list(map(int,input().split()))
print({v:k for k,v in Counter(arr).items()}[1])


5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
8


In [ ]:
for _ in range(int(input())):
  x,a,z,b=input(),set(input().split()),input(),set(input().split())
  print(a.issubset(b))

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 1
False
7
1 2 3 5 6 8 9
3
9 8 2
False


In [ ]:
lis = [2, 1, 3, 5, 4, 3, 8]
del (lis[3:5])
print(lis)
     

[2, 1, 3, 3, 8]


TypeError: ignored

In [ ]:
import math
a,b,m=[int(input()) for _ in "123"]
print(pow(a,b),pow(a,b,m),sep='\n')

3
4
5
81
1


In [ ]:
a,b,c,d=[int(input()) for _ in "1234"]
print(pow(a,b)+pow(c,d))

9
29
7
27
4710194409608608369201743232


In [ ]:
import numpy
print(numpy.eye(8,7,k=1))
print("\r")
print(numpy.eye(8,7,k=-2))

[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]]


In [ ]:
import numpy
print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))


3  3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [ ]:
import numpy
print(numpy.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
n,m=map(int,input().split())
a,b=(np.array([input().split() ],dtype=int) for _ in range(2))
print(a+b,a-b,a*b,a//b,a%b,a**b,sep="\n")

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [ ]:
import numpy as np
n, m = map(int, input().split())
a, b = (np.array([input().split() for _ in range(n)], dtype=int) for _ in range(2))
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

1 4
1 2 3 4
5 6  7  8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [ ]:
from itertools import combinations_with_replacement
s,k=input().split()
for c in combinations_with_replacement(sorted(s),int(k)):
  print(''.join(c))

HACK 2
AA
AC
AH
AK
CC
CH
CK
HH
HK
KK


In [ ]:
from itertools import groupby
print(*[(len(list(c)),int(k)) for k,c in groupby(input())])


12223311
(1, 1) (3, 2) (2, 3) (2, 1)


In [ ]:
s='1222'
len(list(s),int(s))

TypeError: ignored

In [ ]:
N = int(input())
L = input().split()
K = int(input())

C = list(combinations(L, K))
print(C)
F = filter(lambda c: 'a' in c, C)
print(F)
print("{0:.3}".format(len(list(F))/len(C)))

4
a a c d
2
[('a', 'a'), ('a', 'c'), ('a', 'd'), ('a', 'c'), ('a', 'd'), ('c', 'd')]
0.833


In [ ]:
from itertools import product
K,M = map(int,input().split())
N = (list(map(int, input().split()))[1:] for _ in range(K))
results = map(lambda x: sum(i**2 for i in x)%M, product(*N))
print(list(results))
print(max(results))

3 100

sdko


ValueError: ignored

In [ ]:
K,M=map(int,input().split())
N=(list(map(int,input().split()))[1:] for _ in range(k))
results=map(lambda x:sum(i**2 for i in x)%M,product(*N))
print(results)

In [ ]:
n,x=map(int,input().split())
sheet=[]
for _ in range(x):
  sheet.append(map(float,input().split()))
for i in zip(*sheet):
  print(sum(i)/len(i))

5 3
89 90 78 93 80
90 91 85 88 86 
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


In [ ]:
ui = input().split()
x = int(ui[0])
print(eval(input()) == int(ui[1]))

1 4
x**3+x**2+x+1
True


In [ ]:
N,n = int(input()),input().split()
print (all([int(i)>0 for i in n]) and any([j == j[::-1] for j in n]))

5
12 9 61 5 14 
True


In [ ]:
class flashcard:
  def __init__(self,word,meaning):
    self.word=word
    self.meaning=meaning
  def __str__(self):
    return self.word+'('+self.meaning+')'
flash=[]
print("welcome to the flash card aplication")
while(True):
  word=input("enter the name you want to add your flash card")
  meaning=input("enter the meaning add to flash card")
  flash.append(flashcard(word,meaning))
  option=int(input("enter 0 if you want another flash card"))
  if(option):
    break
print("\n flash cards")
for i in flash:
  print(">",i)


welcome to the flash card aplication
enter the name you want to add your flash carddsa
enter the meaning add to flash carddata structures and algos
enter 0 if you want another flash card0
enter the name you want to add your flash cardgfg
enter the meaning add to flash cardgeeks for geeks
enter 0 if you want another flash card1

 flash cards
dsa(data structures and algos) gfg(geeks for geeks) 

In [ ]:
class geeks:
  count=0
  def __init__(self):
    geeks.count+=1
g1=geeks()
g2=geeks()
g3=geeks()
print(geeks.count)


3


In [ ]:
import math
import random
print(random.randint(0,5))
print(random.random())
print(random.random()*100)


0
0.2398227204047496
37.94990655778749


In [ ]:
import os
cwd=os.getcwd()
print("current working directory",cwd)

current working directory /content


In [ ]:
import os
def current_path():
  print("current working directory")
  print(os.getcwd)
  print()
current_path()
os.chdir('../')
current_path()

current working directory
<built-in function getcwd>

current working directory
<built-in function getcwd>



In [1]:
from abc import ABCMeta,abstractmethod
class Book(object,metaclass=ABCMeta):
  def __init__(self,author,title):
    self.author=author
    self.title=title
  @abstractmethod
  def display():
    pass
class MyBook(Book):
  price=0
  def __init__(self,author,title,price):
    self.price=price
    super(Book,self).__init__
  def display(self):
    print("Title :"+ title)
    print("Author :"+ author)
    print("Price :"+ str(price))


title=input()
author=input()
price=int(input())
New_novel=MyBook(author,title,price)
New_novel.display()


The Alchemist
Paulo Coelho
248
Title :The Alchemist
Author :Paulo Coelho
Price :248
