<a href="https://colab.research.google.com/github/srikrishna-stack/python-problem-solving/blob/main/matrix_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#matrix in python
#program to add two matrices 
x=[[1,2,3],[4,5,6],[7,8,9]]
y=[[9,8,7],[6,5,4],[3,2,1]]
res=[[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(x)):
  for j in range(len(x[0])):
    res[i][j]=x[i][j]+y[i][j]
for r in res:
  print(r)
  



[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [ ]:
#matrix multiplication
x = [[1, 7, 3],
    [3, 5, 6],
    [6, 8, 9]]
Y = [[1, 1, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]     
res=[[0,0,0],
    [0,0,0],
    [0,0,0]]
for i in range(len(x)):
  for j in range(len(x[0])):
    for k in range(len(y)):
      res[i][j]+=x[i][k]*y[k][j]
for r in res:
  print(r)       


[60, 49, 38]
[75, 61, 47]
[129, 106, 83]


In [ ]:
#product of a matrix
def prod(val):
  res=1
  for ele in val:
    res*=ele
  return res
test_list = [[1, 4, 5], [7, 3], [4], [46, 7, 3]]
print("The original list : " + str(test_list))
res = prod ([ele for sub in test_list for ele in sub])
print("the total no of product in the list is",res)
  


The original list : [[1, 4, 5], [7, 3], [4], [46, 7, 3]]
the total no of product in the list is 1622880


In [ ]:
#addition and subtraction of a matrix using numpy
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)
print("addition of matrices")
print(np.add(a,b))
print("subtraction of matrices")
print(np.subtract(a,b))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
addition of matrices
[[ 6  8]
 [10 12]]
subtraction of matrices
[[-4 -4]
 [-4 -4]]


In [ ]:
#transpose of a matrix
m=[[1,2],[3,4],[5,6]]
for row in m:
  print(row)
res=[[m[j][i] for j in range(len(m))]for i in range(len(m[0]))]
print("the transpose of a matrix")
for row in res:
  print(row)
print("\n")
#using numpy
import numpy 
matrix=[[1,2,3],[4,5,6]]
print(matrix)
print("\n")
print("transpose of a matrix using numpy")
print(numpy.transpose(matrix))

[1, 2]
[3, 4]
[5, 6]
the transpose of a matrix
[1, 3, 5]
[2, 4, 6]


[[1, 2, 3], [4, 5, 6]]


transpose of a matrix using numpy
[[1 4]
 [2 5]
 [3 6]]


Many times while working with numbers in data science we come across the problem in which we need to work with data science we need to transform a number to a **matrix**

In [ ]:
#transformation of numbers to matrices
N=4
print("the dimension ", N)
res=[list(range(1+N*i,1+N*(i+1))) for i in range(N)]
print("the created matrix ", res)


the dimension  4
the created matrix  [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


Sometimes, while working with Python Matrix, one can have a problem in which one needs to find the Kth column of Matrix. This is a very popular problem in Machine Learning Domain and having solution to this is useful

In [29]:
#fetching the kth value using list comprehsion
list1=[[4,5,6],[1,2,3],[9,8,7]]
k=2
result=[i[k] for i in list1]
print(result)


[6, 3, 7]
